rustfoundation/foundation.rust-lang.org

css/index.css
Congratulations on the foundation!!!
The site looked a little funky on mobile and I figured out it was due to some header stuff- this is a change that converts the header to flexbox so it can wrap on narrower screen sizes.
I also put a minimum height on `<main>` so the footer doesn't float halfway up the screen on short pages.
=> clean up header for mobile and set minimum page height based on viewport

css/index.css
This improves the **color contract** for the **hovering state of nav item links that have not been visited yet**, by changing the color to "white".
Currently, the nav item links that are in hovering state and have not been visited yet have a color of "orange".
This orange color blends in with the background color in the header, which makes the nav item links hard to see.
There is another (new) selector that could be used:
```css
header a[href] {
...
}
```
Why is this highlighted? Because there is already a selector, which is for header links **:visited** (see [line 85](https://github.com/rust-lang/foundation.rust-lang.org/blob/8330295db9a0fa5725efc1ca8f3cabc4769639d5/css/index.css#L85)):
```css
header a[href]:visited {
color: var(--lightgrey);
}
```
Keep in mind that currently "white" is …
=> improve contrast for nav link on hover not visited

policies/privacy-policy.md
As of rust-lang/crates.io#3141, crates.io now self-hosts Chart.js.
r? @ashleygwilliams
=> Drop Google Visualization API from policy page

.github/FUNDING.yml
Currently github has a sponsor button, but for 11ty, because of the template
=> Remove 11ty sponsor link

_includes/layouts/base.njk, _includes/layouts/home.njk
The Rust Foundation has a mission to support Rust maintainers. We require various levels of feedback to do our job well and thus propose adding the collection of basic website analytics, particularly page views, in order to understand what content works well and what the Foundation should be focused on producing. We suggest a solution called [Plausible](https://plausible.io) that provides privacy-friendly analytics.
The Rust Foundation’s mission is to steward the Rust programming language and ecosystem. In order to excel at this, we require various levels of data and feedback to ensure it is focusing its resources appropriately. And one of the key areas of data is derived from our online presence.
We maintain a [website](https://foundation.rust-lang.org) as a vehicle for Foundation news …
=> Add Analytics

news/2021-11-16-news-announcing-cloud-compute-initiative.md
Putting it on our website as well as [external](https://www.businesswire.com/news/home/20211116005828/en/Rust-Foundation-Announces-Cloud-Compute-Program)
=> [News] Announcing Cloud Compute Initiative

index.njk
Just keeping the become a member button on the front page as we have grown our assets across the site to learn more about the Foundation through a bunch of different paths and channels.
=> Refresh home page with just one button

_includes/memberslist-small.njk
After updating member imaging handling for CloudCannon, forgot to update home page path.
=> Fix home page member images

_includes/layouts/redirect.njk, board.njk
Since we are currently using GitHub Pages, we don't have server side infrastructure for 301-type redirects right now. Until we move hosting to something that supports this, we can use client redirects as a workaround
Ref: https://github.com/11ty/eleventy/issues/510#issuecomment-630682384
=> Add client side redirect for removed Board page

css/index.css
When you hover over a link in the footer, it turns the same color as the background and cannot be read. This patch makes it stay white instead.
It also removes a superfluous `footer a[href]:visited` selector.
=> Fix bug in footer link hover color

_includes/layouts/redirect.njk, news/2022-03-16-news-announcing-three-new-board-members.md, redirects.md
Adds one redirect.md file to put all client side redirects. That way we can keep things tidy until if and when we move to a server side system.
(Also removed the press tag from the three new board member post so it doesn't show up twice on the News page)
=> A bit more concise redirect listing

css/index.css
* uses a variable font size based on viewport width for the splash-sized header, starting at viewports 640px and narrower
=> use a smaller splash font size on smaller screens

news/new-slsa-survey-reveals-real-world-developer-approaches-to-software-supply-chain-security.md
Just noticed this looking at the live post:
=> Fix broken heading in the SLSA blog post

policies/cloud-compute-program.md
This makes it easier to find for new contributors, since foundation.rust-lang.org seems to have better SEO than forge.
=> Link to the docs on the Cloud Compute desktops from the policy page

news/rewarding-resilience-rust-the-u-s-national-cybersecurity-strategy.md
Using the `advisors` tag in the rewarding resilience blog post made it so that it was also added as an image in the Distinguished Advisors on the About page because those images are sorted by an `advisors` tag too. Change the blog tag to `distinguished advisors`.
=> Fix rogue distinguished advisor

news/a-note-on-data-retention-data-privacy-standards-from-the-crates-io-team.md
Similar to previous crates.io posts I've added the `crates.io` tag to the post and I've also adjusted the `byline` field, which #415 will enable us to show again.
=> Adjust metadata for latest crates.io guest blog post

_includes/layouts/news.njk, css/index.css
This somehow went missing when we moved from "posts" to "news" (see https://github.com/rustfoundation/foundation.rust-lang.org/pull/176) and broke a few older posts that were using this field.
Example:
(the "by Rust Foundation Board of Directors" line)
=> layouts/news: Add missing `byline`

.github/workflows/publish.yml
This PR is roughly similar to https://github.com/rust-lang/rfcs/pull/3419. Instead of using the `gh-pages` branch, afterwards we will deploy directly from GitHub Actions and the generated artifact of the `build` job.
As mentioned in the linked PR, we will need to slightly adjust the repo settings for this to work properly.
=> CI: Use actions/deploy-pages to deploy

board/markrousskov.md, board/ryanlevick.md
I'm admittedly assuming that the existing Core verbiage is a reference to the since dissolved Core Team, and that it could/should probably be updated to reflect such, as well as that Mark and Ryan are now also on the Leadership Council.
Happy to change or close this if this was an incorrect assumption though
=> replace "Core" with "Leadership Council"

.github/workflows/publish.yml
v2 of `cache` is going to stop working. 
> Starting February 1st, 2025, we are closing down v1-v2 of actions/cache (read more about it in this changelog announcement) as well as all previous versions of the @actions/cache package in actions/toolkit. Attempting to use a version of the @actions/cache package or actions/cache after the announced deprecation date will result in a workflow failure. If you are pinned to a specific version or SHA of the cache action, your workflows will also fail after February 1st.
> 
> What you need to do:
> We strongly encourage you to update your workflows to begin using a supported version of actions/cache, and upgrade your actions or other products that depend on the @actions/cache package to 4.0.0 or above.
> 
> Supported versions and tags:
> 
> …
=> Update version of actions/cache

news/rust-foundation-in-review-2024-annual-report-preview.md
I think there was a little `typo` with the `Adorsys` spelling
=> fixed: typo
